[package]
name = "bd_server"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rconn = "0.4"
imlogger = "0.1"
sha2 = "0.10"
aes-gcm = "0.10"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
rand = "0.9"
